server:
  context-path: /dt
  port: 8081
#配置redis
spring:
  redis:
    port: 6379
    host: www.dongchao.com
    database: 1
    password:
    pool:
      max-active: 10
      min-idle: 0
    timeout: 10000
#配置mysql驱动
  datasource:
    url: jdbc:mysql://localhost:3306/dt?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: dongchao
    password: 920204
    schema: classpath:sql/mysql-schema.sql
#database pool,默认使用tomcat数据源，此处指定为druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# spring batch
#将enabled设置为true，禁止spring batch在启动执行所有批处理任务,因为实际环境会交给定时器或者手动触发批处理
  batch:
    job:
      enabled: false
#AMQP
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  http:
    multipart:
      enabled: true
      max-file-size: -1 #-1表示不限制上传文件大小
      location: C:\tmp\upload
